modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="extra_stuff"
version="1.0.0"
displayName="Extra Stuff"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://minersonline.uk"
authors="ajh123"
description='''
A Minecraft Mod adding extra stuff
'''

[[dependencies.extra_stuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




